anykernel_SmartPack: switch to AnyKernel3
Includes all the commits till June 3, 2019, 10AM KST.
Credits: osm0sis
Ref: https://github.com/osm0sis/AnyKernel3

Signed-off-by: sunilpaulmathew <sunil.kde@gmail.com>

diff --git a/anykernel_SmartPack/META-INF/com/google/android/update-binary b/anykernel_SmartPack/META-INF/com/google/android/update-binary
--- a/anykernel_SmartPack/META-INF/com/google/android/update-binary
+++ b/anykernel_SmartPack/META-INF/com/google/android/update-binary
@@ -1,10 +1,13 @@
 #!/sbin/sh
-# AnyKernel2 Backend (DO NOT CHANGE)
+# AnyKernel3 Backend (DO NOT CHANGE)
 # osm0sis @ xda-developers
 
 OUTFD=/proc/self/fd/$2;
 ZIPFILE="$3";
-DIR=`dirname "$ZIPFILE"`;
+DIR=$(dirname "$ZIPFILE");
+
+test "$home" || home=/tmp/anykernel;
+parent=$(dirname $home);
 
 ui_print() {
   until [ ! "$1" ]; do
@@ -24,27 +27,26 @@ int2ver() {
   fi;
 }
 cleanup() {
-  cd /tmp;
-  rm -rf /tmp/anykernel;
+  cd $parent;
+  rm -rf $home;
 }
 debugging() {
   case $(basename "$ZIPFILE" .zip) in
     *-debugging)
-      ui_print " ";
-      ui_print "Creating debugging archive in zip directory...";
-      $bb tar -czvf "$DIR/anykernel2-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" /tmp/*;
+      ui_print " " "Creating debugging archive in zip directory...";
+      $bb tar -czvf "$DIR/anykernel3-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" $parent/*;
     ;;
   esac;
 }
 is_mounted() { $bb mount | $bb grep " $1 "; }
 unmount_all() {
-  (umount /system;
+  ($bb umount /system;
   if [ -d /system_root -a ! -f /system/build.prop ]; then
-    umount /system_root;
+    $bb umount /system_root;
   fi;
-  umount /system;
-  umount /vendor;
-  umount /data) 2>/dev/null;
+  $bb umount /system;
+  $bb umount /vendor;
+  $bb umount /data) 2>/dev/null;
 }
 abort() {
   ui_print "$*";
@@ -59,23 +61,27 @@ abort() {
 show_progress 1.34 4;
 ui_print " ";
 cleanup;
-mkdir -p /tmp/anykernel/bin;
-cd /tmp/anykernel;
+mkdir -p $home/bin;
+cd $home;
 unzip -o "$ZIPFILE";
-if [ $? != 0 -o -z "$(ls tools)" ]; then
+if [ $? != 0 -o ! "$(ls tools)" ]; then
   abort "Unzip failed. Aborting...";
 fi;
-bb=/tmp/anykernel/tools/busybox;
+bb=$home/tools/busybox;
 chmod 755 $bb;
 $bb chmod -R 755 tools bin;
+$bb --install -s bin;
+if [ $? != 0 -o -z "$(ls bin)" ]; then
+  abort "Busybox setup failed. Aborting...";
+fi;
 
 if [ -f banner ]; then
   while IFS='' read -r line || $bb [[ -n "$line" ]]; do
     ui_print "$line";
   done < banner;
-  ui_print " ";
-  ui_print " ";
+  ui_print " " " ";
 fi;
+
 
 ui_print "SmartPack-Kernel $(cat /tmp/anykernel/ramdisk/version) for Oneplus 5/5T";
 if [ -f /tmp/anykernel/version ]; then
@@ -86,6 +92,7 @@ fi;
 ui_print " ";
 ui_print "...(c) sunilpaulmathew@xda-developers.com...";
 ui_print " ";
+ui_print " " "AnyKernel3 by osm0sis @ xda-developers" " " " ";
 ui_print " ";
 
 unmount_all;
@@ -95,8 +102,8 @@ fi;
 ($bb mount -o ro -t auto /vendor;
 $bb mount /data) 2>/dev/null;
 if [ -f /system/system/build.prop ]; then
-  umount /system;
-  (umount /system;
+  $bb umount /system;
+  ($bb umount /system;
   mkdir /system_root) 2>/dev/null;
   $bb mount -o ro -t auto /dev/block/bootdevice/by-name/system /system_root;
   $bb mount -o bind /system_root/system /system;
@@ -129,7 +136,7 @@ if [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ]; then
       break;
     fi;
   done;
-  ui_print "Device is compatible...";
+  ui_print " ";
   if [ ! "$match" ]; then
     abort "Unsupported device. Aborting...";
   fi;
@@ -154,8 +161,7 @@ if [ "$supported_ver" ]; then
     done;
   fi;
   if [ "$supported" ]; then
-    ui_print "$android_ver";
-    ui_print " ";
+    ui_print "$android_ver" " ";
   else
     ui_print " ";
     abort "Unsupported Android version. Aborting...";
@@ -163,23 +169,18 @@ if [ "$supported_ver" ]; then
 fi;
 
 ui_print "Installing...";
-for i in $($bb --list); do
-  $bb ln -s $bb bin/$i;
-done;
-if [ $? != 0 -o -z "$(ls bin)" ]; then
-  abort "Recovery busybox setup failed. Aborting...";
-fi;
-PATH="/tmp/anykernel/bin:$PATH" $bb ash anykernel.sh $2;
+core=$($bb grep -oE 'ak.*core.sh' anykernel.sh);
+test -f tools/$core || $bb ln -s $home/tools/ak*-core.sh $home/tools/$core;
+PATH="$home/bin:$PATH" home=$home $bb ash anykernel.sh $2;
 if [ $? != 0 ]; then
   abort;
 fi;
 
 if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
-  ui_print " ";
-  ui_print "Pushing modules...";
+  ui_print " " "Pushing modules...";
   $bb mount -o rw,remount -t auto /system;
   $bb mount -o rw,remount -t auto /vendor 2>/dev/null;
-  cd /tmp/anykernel/modules;
+  cd $home/modules;
   for module in $(find . -name '*.ko'); do
     modtarget=$(echo $module | $bb cut -c2-);
     if [ ! -e $modtarget ]; then
@@ -202,7 +203,7 @@ if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
       $bb mount -o ro,remount -t auto $modtarget;
     fi;
   done;
-  cd /tmp/anykernel;
+  cd $home;
   $bb mount -o ro,remount -t auto /system;
   $bb mount -o ro,remount -t auto /vendor 2>/dev/null;
 fi;
@@ -218,6 +219,4 @@ test "$savedpre" && export LD_PRELOAD="$savedpre";
 
 unmount_all;
 
-ui_print " ";
-ui_print " ";
-ui_print "Done!";
+ui_print " " " " "Done!";
